#!/usr/bin/env bash
set -euo pipefail
set +u
source "/opt/ros/${ROS_DISTRO:-humble}/setup.bash"
source /ros2_ws/install/setup.bash
set -u
exec ros2 launch realsense2_camera rs_launch.py \
  enable_color:=true \
  enable_depth:=true \
  rgb_camera.profile:=640x480x30 \
  depth_module.profile:=1024x768x30 \
  pointcloud.enable:=true \
  enable_sync:=true \
  align_depth.enable:=true
